#include "./parser.h"

// Prepopulated much in advance
typedef enum {
  ERROR_TYPE_UNKNOWN,

  ERROR_TYPE_UNDEFINED_IDENTIFIER,
  ERROR_TYPE_REDEFINED_IDENTIFIER,
  ERROR_TYPE_INVALID_SCOPE_ACCESS,

  ERROR_TYPE_TYPE_MISMATCH,
  ERROR_TYPE_RETURN_TYPE_MISMATCH,

  ERROR_TYPE_ASSIGN_TO_CONST,
  ERROR_TYPE_ASSIGN_TYPE_MISMATCH,
  ERROR_TYPE_ASSIGN_TO_UNDECLARED,

  ERROR_TYPE_FUNCTION_ARGUMENT_COUNT_MISMATCH,
  ERROR_TYPE_FUNCTION_ARGUMENT_TYPE_MISMATCH,
  ERROR_TYPE_CALL_NON_FUNCTION,

  ERROR_TYPE_UNARY_OPERATOR_TYPE_INVALID,
  ERROR_TYPE_BINARY_OPERATOR_TYPE_INVALID,

  ERROR_TYPE_CONDITION_NOT_BOOLEAN,

  ERROR_TYPE_EXPECTED_INT,
  ERROR_TYPE_EXPECTED_STRING,
  ERROR_TYPE_EXPECTED_CHAR,
  ERROR_TYPE_EXPECTED_BOOL,

  ERROR_TYPE_INVALID_CAST,
  ERROR_TYPE_IMPLICIT_CAST_DISALLOWED,

  ERROR_TYPE_ARRAY_INDEX_NOT_INT,
  ERROR_TYPE_INDEX_OUT_OF_BOUNDS,

  ERROR_TYPE_MEMBER_ACCESS_ON_NON_STRUCT,
  ERROR_TYPE_UNKNOWN_MEMBER,

  ERROR_TYPE_CONST_ASSIGNMENT,
  ERROR_TYPE_CONST_REASSIGNMENT,

  ERROR_TYPE_MISSING_RETURN_STATEMENT,
  ERROR_TYPE_UNREACHABLE_CODE,

  ERROR_TYPE_VOID_VALUE_USED,
  ERROR_TYPE_DISALLOWED_VOID_CONTEXT,

  ERROR_TYPE_DUPLICATE_PARAMETER,
  ERROR_TYPE_PARAMETER_TYPE_MISMATCH,

  ERROR_TYPE_TYPE_INFERENCE_FAILURE,
  ERROR_TYPE_GENERIC_RESOLUTION_FAILURE,

  ERROR_TYPE_INVALID_INITIALIZER,
  ERROR_TYPE_INITIALIZER_TYPE_MISMATCH,

  ERROR_NO_ERROR // for success return types
} ErrorCode;

typedef struct {
    const char* file;
    const char* func;
    size_t line;
} TraceFrame;

typedef struct {
    TraceFrame* items;
    size_t size;
    size_t capacity;
} Trace;

typedef struct {
    ErrorCode code;
    Trace trace;
    char message[128];
    TokenPos pos;
} Error;

typedef struct {
  Error* items;
  size_t size;
  size_t capacity;
} ErrorStack;

/// `tokens` is necessary for the error messages
void typecheck_prog(SymbolTable* table, NodeProg* prog, Tokens* tokens);
